# Generated by Django 4.0.1 on 2022-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='model_image',
            field=models.ImageField(default='20210705_142228_nVU7iYa.jpg', upload_to='model_images/'),
        ),
    ]
